"""Tests for textbrush/references/ (epic multi-reference-flux-image-editing, S3).

Covers:
  - AC-PROCESS-1: EXIF orientation, RGB conversion, uniform (equal-axis)
    scaling, full content retention, no crop, no facial analysis.
  - AC-PROCESS-2: deterministic centered padding with the documented
    neutral fill, alpha compositing onto that same fill, determinism
    across repeated runs, actionable errors instead of degraded output.
  - AC-INPUT-3: the full per-file failure taxonomy (unsupported extension,
    missing, unreadable, corrupt, decode-resource-constrained), matched
    case-insensitively.
  - The NormalizedReference seam contract's exact field set, consumed
    verbatim by S5 and S7.

Fixtures under tests/fixtures/images/ are committed files generated by
scripts/generate_reference_fixtures.py, which independently verifies at
generation time that every "corrupt" fixture actually fails to decode via
the real PIL decoder (VQ-S3-001) -- these tests reuse those same files
rather than mocking `open()` or PIL (VQ-S3-006, VQ-S3-009).
"""

from __future__ import annotations

import datetime
import os
import shutil
import warnings
from pathlib import Path

import hypothesis.strategies as st
import pytest
from hypothesis import given, settings
from PIL import Image

# F13: the module was renamed from normalize.py to normalization.py
# precisely so this import is a plain, ordinary module import -- the old
# name collided with its own primary export (`textbrush.references.normalize`
# meant both the submodule and, after __init__'s `from .normalize import
# normalize` re-export, the function), which required routing through
# importlib/sys.modules to reliably get the module object rather than the
# function it shared a name with.
import textbrush.references.normalization as normalize_module
from tests.test_config import _internal_imports
from textbrush.references import (
    NEUTRAL_FILL_VALUE,
    SUPPORTED_EXTENSIONS,
    CorruptReferenceError,
    NormalizationError,
    NormalizedReference,
    ReferenceImageError,
    ReferenceNotFoundError,
    ReferenceResourceConstrainedError,
    UnreadableReferenceError,
    UnsupportedExtensionError,
    normalize,
)

FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures" / "images"

_FILL_RGB = (NEUTRAL_FILL_VALUE, NEUTRAL_FILL_VALUE, NEUTRAL_FILL_VALUE)


def test_neutral_fill_value_pinned_to_documented_constant():
    """Every fill-color assertion in this file derives `_FILL_RGB` from the
    imported `NEUTRAL_FILL_VALUE`, so changing the constant to any other
    value would still pass the whole suite -- this is the one assertion
    that pins the constant itself, rather than re-deriving from it. 128 does
    not yet appear in any user-facing doc (AC-DOC-1); closing that gap is
    S13's responsibility, not this story's -- this test only guards against
    the constant silently drifting away from what S13 will eventually
    document."""
    assert NEUTRAL_FILL_VALUE == 128


def _content_bounding_box(image: Image.Image, *, tolerance: int = 8) -> tuple[int, int, int, int]:
    """Return (min_x, min_y, max_x, max_y) of pixels that differ from the
    neutral fill color by more than `tolerance` on any channel.

    Used to measure the actual pasted content region on a padded canvas
    without relying on the implementation's own internal math -- a per-axis
    independent stretch bug (forbidden by AC-PROCESS-1/2) would leave NO
    fill-colored border on the axis it wrongly stretched, which this
    bounding box directly reveals.
    """
    pixels = image.load()
    width, height = image.size
    min_x, min_y, max_x, max_y = width, height, -1, -1
    for y in range(height):
        for x in range(width):
            r, g, b = pixels[x, y][:3]
            if (
                abs(r - _FILL_RGB[0]) > tolerance
                or abs(g - _FILL_RGB[1]) > tolerance
                or abs(b - _FILL_RGB[2]) > tolerance
            ):
                min_x, min_y = min(min_x, x), min(min_y, y)
                max_x, max_y = max(max_x, x), max(max_y, y)
    assert max_x >= 0, "no non-fill content found on canvas"
    return min_x, min_y, max_x, max_y


class TestModuleBoundary:
    """architecture.md boundary rule 2: `references` is a leaf and must not
    import backend, worker, or ipc. Verified via an actual AST-based
    import-graph check (VQ-S3-002, VQ-S3-003), not a manual claim -- reusing
    the exact helper and forbidden-set convention tests/test_config.py
    established for this purpose."""

    def test_normalize_module_has_no_forbidden_internal_imports(self):
        source = Path(normalize_module.__file__).read_text()
        internal_imports = _internal_imports(source)

        forbidden = {"textbrush.backend", "textbrush.worker", "textbrush.ipc"}
        violations = {
            i for i in internal_imports if any(i == f or i.startswith(f + ".") for f in forbidden)
        }
        assert not violations, (
            f"references/normalization.py must not import {forbidden}; found {violations}"
        )

        # references also holds no per-model dimension table of its own
        # (architecture.json's signature_decision): it does not import
        # `model`, `config`, `cli`, or `inference` either.
        assert internal_imports == set(), (
            "references/normalization.py should have zero internal textbrush.* "
            f"dependencies; found {internal_imports}"
        )

    def test_init_module_has_no_forbidden_internal_imports(self):
        import textbrush.references as references_package

        source = Path(references_package.__file__).read_text()
        internal_imports = _internal_imports(source)

        forbidden = {"textbrush.backend", "textbrush.worker", "textbrush.ipc"}
        violations = {
            i for i in internal_imports if any(i == f or i.startswith(f + ".") for f in forbidden)
        }
        assert not violations, (
            f"references/__init__.py must not import {forbidden}; found {violations}"
        )
        assert internal_imports <= {"textbrush.references.normalization"}


class TestFailureTaxonomy:
    """AC-INPUT-3: each failure class uses a real fixture exhibiting that
    exact failure mode, not a mocked open() call (VQ-S3-009)."""

    def test_unsupported_extension_real_decodable_file_rejected_by_extension(self):
        """unsupported_extension.bmp is a real, decodable image -- it must
        be rejected purely on its extension, proving the check is
        extension-based and not merely 'decode failed'."""
        path = FIXTURES_DIR / "unsupported_extension.bmp"
        assert path.exists()
        # Sanity: PIL itself can decode this file -- if normalize() rejects
        # it, that must be the extension check, not an incidental decode error.
        with Image.open(path) as img:
            img.load()

        with pytest.raises(UnsupportedExtensionError, match=r"\.bmp"):
            normalize(path, target_size=(64, 64))

    def test_missing_file_raises_reference_not_found(self, tmp_path: Path):
        missing = tmp_path / "does_not_exist.png"
        assert not missing.exists()

        with pytest.raises(ReferenceNotFoundError):
            normalize(missing, target_size=(64, 64))

    def test_unreadable_file_raises_unreadable_reference_error(self, tmp_path: Path):
        if os.name != "posix":
            pytest.skip("permission-bit test requires a POSIX filesystem")
        if hasattr(os, "getuid") and os.getuid() == 0:
            pytest.skip("root bypasses permission bits; cannot exercise this failure as root")

        source = FIXTURES_DIR / "valid_landscape.jpg"
        unreadable = tmp_path / "unreadable.jpg"
        shutil.copy(source, unreadable)
        unreadable.chmod(0o000)
        try:
            with pytest.raises(UnreadableReferenceError):
                normalize(unreadable, target_size=(64, 64))
        finally:
            unreadable.chmod(0o644)

    @pytest.mark.parametrize(
        "fixture_name",
        ["corrupt_truncated.jpg", "corrupt_not_an_image.png", "corrupt_empty.jpg"],
    )
    def test_corrupt_files_raise_corrupt_reference_error(self, fixture_name: str):
        path = FIXTURES_DIR / fixture_name
        assert path.exists()

        with pytest.raises(CorruptReferenceError):
            normalize(path, target_size=(64, 64))

    def test_decode_resource_constrained_raises_actionable_error(self, monkeypatch):
        """Lowers Pillow's real decompression-bomb guard (MAX_IMAGE_PIXELS)
        below the fixture's actual pixel count and confirms the REAL
        decoder's real safety mechanism fires -- not a simulated failure --
        satisfying VQ-S3-001's 'verified independently of the test harness'
        for this failure class without committing a multi-hundred-megapixel
        fixture to the repository."""
        path = FIXTURES_DIR / "valid_square.png"  # 400x400 = 160,000 pixels
        monkeypatch.setattr(Image, "MAX_IMAGE_PIXELS", 100)

        with pytest.raises(ReferenceResourceConstrainedError):
            normalize(path, target_size=(64, 64))

    def test_decompression_bomb_warning_tier_also_raises_resource_constrained_error(
        self, monkeypatch
    ):
        """F4: Pillow's decompression-bomb guard has two tiers gated on
        MAX_IMAGE_PIXELS -- above 2x it raises DecompressionBombError
        (covered by the test above), but between 1x and 2x it only emits a
        DecompressionBombWarning and, by default, proceeds to decode
        anyway. At the ratio used here (400x400 = 160,000 pixels against a
        100,000-pixel ceiling, exactly 1.6x) only the warning tier fires;
        without _decode()'s warnings-as-errors promotion this call would
        silently succeed, and under a warnings-as-errors interpreter
        setting it would instead raise a bare DecompressionBombWarning
        outside the ReferenceImageError hierarchy -- which S7's
        acknowledgement-time handler (AC-STATE-3, AC-RECOVERY-1) would not
        catch."""
        path = FIXTURES_DIR / "valid_square.png"  # 400x400 = 160,000 pixels
        monkeypatch.setattr(Image, "MAX_IMAGE_PIXELS", 100_000)  # 1.6x ratio

        with pytest.raises(ReferenceResourceConstrainedError):
            normalize(path, target_size=(64, 64))

    def test_decompression_bomb_warning_tier_raises_under_host_warnings_as_errors(
        self, monkeypatch
    ):
        """Round 3 finding C2: round 2 (N3) correctly removed the
        thread-unsafe global-filter mutation from production code, but in
        doing so also dropped `DecompressionBombWarning` from `_decode`'s
        `except` clause -- reopening the original gap in a narrower form.
        When the HOST APPLICATION (not this module) has independently
        configured `warnings.simplefilter("error",
        Image.DecompressionBombWarning)`, `Image.open()` raises the
        warning as an exception from INSIDE itself, before `_decode`'s
        header-size check ever runs -- so without the restored `except`
        clause this would escape as a bare `DecompressionBombWarning`
        outside the `ReferenceImageError` hierarchy, uncatchable by S7's
        acknowledgement-time handler (AC-STATE-3, AC-RECOVERY-1). The
        warnings-as-errors filter here is configured by THIS TEST, scoped
        to the `with` block via `catch_warnings()`, never by production
        code -- exercising exactly the host configuration this finding is
        about, distinct from round 2's test above which covers only the
        default (non-warnings-as-errors) case."""
        path = FIXTURES_DIR / "valid_square.png"  # 400x400 = 160,000 pixels
        monkeypatch.setattr(Image, "MAX_IMAGE_PIXELS", 100_000)  # 1.6x ratio

        with warnings.catch_warnings():
            warnings.simplefilter("error", Image.DecompressionBombWarning)
            with pytest.raises(ReferenceResourceConstrainedError):
                normalize(path, target_size=(64, 64))

    def test_resource_constrained_failure_does_not_return_degraded_result(self, monkeypatch):
        """A resource failure must raise, never silently return a cropped,
        stretched, or substituted NormalizedReference (spec.md sec 6.2)."""
        path = FIXTURES_DIR / "valid_square.png"
        monkeypatch.setattr(Image, "MAX_IMAGE_PIXELS", 100)

        result = None
        try:
            result = normalize(path, target_size=(64, 64))
        except ReferenceResourceConstrainedError:
            pass
        assert result is None

    def test_normalization_stage_failure_raises_normalization_error(self, monkeypatch):
        """A failure during scale/pad (as opposed to decode) is reported as
        NormalizationError, distinct from the decode-time taxonomy."""
        monkeypatch.setattr(
            normalize_module,
            "_scale_and_pad",
            lambda *args, **kwargs: (_ for _ in ()).throw(MemoryError()),
        )

        with pytest.raises(NormalizationError):
            normalize(FIXTURES_DIR / "valid_landscape.jpg", target_size=(64, 64))

    def test_all_taxonomy_errors_share_reference_image_error_base(self):
        for cls in (
            UnsupportedExtensionError,
            ReferenceNotFoundError,
            UnreadableReferenceError,
            CorruptReferenceError,
            ReferenceResourceConstrainedError,
            NormalizationError,
        ):
            assert issubclass(cls, ReferenceImageError)


class TestCaseInsensitiveExtensionMatching:
    """AC-INPUT-3: 'IMG_1234.JPG' (an actual on-disk uppercase extension,
    not a lowercased path string built only in the test) must be accepted
    (VQ-S3-006)."""

    def test_uppercase_extension_file_is_accepted(self):
        path = FIXTURES_DIR / "IMG_1234.JPG"
        assert path.exists()
        assert path.suffix == ".JPG"  # literal on-disk extension is uppercase

        result = normalize(path, target_size=(64, 64))

        assert isinstance(result, NormalizedReference)

    @pytest.mark.parametrize("extension", sorted(SUPPORTED_EXTENSIONS))
    def test_every_supported_extension_accepted_in_uppercase_and_lowercase(
        self, tmp_path: Path, extension: str
    ):
        # Each candidate extension is paired with a source fixture whose
        # actual encoded format matches it -- renaming a JPEG's bytes to
        # ".png" would fail to decode as PNG and test the wrong thing.
        source = FIXTURES_DIR / (
            "valid_landscape.jpg" if extension != ".png" else "valid_square.png"
        )
        for candidate_ext in (extension, extension.upper()):
            candidate = tmp_path / f"ref{candidate_ext}"
            shutil.copy(source, candidate)
            result = normalize(candidate, target_size=(32, 32))
            assert isinstance(result, NormalizedReference)


class TestNormalizedReferenceContract:
    """VQ-S3-010: every seam-contract field is present and independently
    checkable, not just pixel_data."""

    def test_all_seam_fields_present_and_correct(self):
        result = normalize(FIXTURES_DIR / "valid_landscape.jpg", target_size=(128, 128))

        assert isinstance(result, NormalizedReference)
        assert isinstance(result.pixel_data, Image.Image)
        assert result.pixel_data.mode == "RGB"
        assert result.pixel_data.size == (128, 128)
        assert result.width == 128
        assert result.height == 128
        assert result.content_aspect_ratio == pytest.approx(600 / 400)
        assert result.fill_value == NEUTRAL_FILL_VALUE
        # decoded_at is a real, parseable ISO-8601 timestamp.
        datetime.datetime.fromisoformat(result.decoded_at)

    def test_content_aspect_ratio_measured_on_content_not_padded_canvas(self):
        """A non-square source padded onto a square canvas must report the
        SOURCE aspect ratio, not 1.0 (AC-PROCESS-1)."""
        result = normalize(FIXTURES_DIR / "valid_landscape.jpg", target_size=(500, 500))

        assert result.content_aspect_ratio == pytest.approx(600 / 400)
        assert result.content_aspect_ratio != pytest.approx(1.0)


class TestUniformScalingAndPadding:
    """AC-PROCESS-1/AC-PROCESS-2: a single scale factor is applied to both
    axes; any remainder is centered padding, never an independent per-axis
    resize. The bounding-box measurement below would fail under a per-axis
    stretch bug: that bug fills the ENTIRE canvas with content on both
    axes whenever source and target aspect ratios differ, leaving no fill
    border to detect."""

    @pytest.mark.parametrize(
        "fixture_name,source_size,target_size",
        [
            ("valid_landscape.jpg", (600, 400), (256, 256)),  # wide source, square target
            ("valid_portrait.png", (300, 500), (256, 256)),  # tall source, square target
            ("valid_square.png", (400, 400), (300, 500)),  # square source, tall target
            ("valid_landscape.jpg", (600, 400), (1024, 768)),  # 3:2 -> 4:3
        ],
    )
    def test_scale_factor_equal_on_both_axes(
        self, fixture_name: str, source_size: tuple[int, int], target_size: tuple[int, int]
    ):
        source_w, source_h = source_size
        target_w, target_h = target_size
        expected_scale = min(target_w / source_w, target_h / source_h)
        expected_content_w = round(source_w * expected_scale)
        expected_content_h = round(source_h * expected_scale)

        result = normalize(FIXTURES_DIR / fixture_name, target_size=target_size)

        min_x, min_y, max_x, max_y = _content_bounding_box(result.pixel_data)
        measured_w = max_x - min_x + 1
        measured_h = max_y - min_y + 1

        assert measured_w == expected_content_w
        assert measured_h == expected_content_h

        # Centered: symmetric padding on each axis (within 1px for an odd remainder).
        left_margin = min_x
        right_margin = target_w - 1 - max_x
        assert abs(left_margin - right_margin) <= 1
        top_margin = min_y
        bottom_margin = target_h - 1 - max_y
        assert abs(top_margin - bottom_margin) <= 1

    def test_odd_remainder_padding_tiebreak_is_deterministic_right_bottom(self):
        """Documented tie-break: floor division for left/top means a single
        extra pixel of remainder lands on the right/bottom."""
        result = normalize(FIXTURES_DIR / "valid_landscape.jpg", target_size=(601, 400))

        min_x, _, max_x, _ = _content_bounding_box(result.pixel_data)
        # source is 600x400 -> target (601, 400): scale = min(601/600, 1) = 1.0,
        # content width 600, remainder 1 on the width axis.
        assert min_x == 0
        assert max_x == 599

    def test_exact_matching_aspect_ratio_produces_no_padding(self):
        """When source and target share the same aspect ratio, the content
        fills the entire canvas -- no fill-colored border at all."""
        result = normalize(FIXTURES_DIR / "valid_square.png", target_size=(200, 200))

        min_x, min_y, max_x, max_y = _content_bounding_box(result.pixel_data)
        assert (min_x, min_y) == (0, 0)
        assert (max_x, max_y) == (199, 199)

    def test_extreme_aspect_ratio_rounds_to_zero_raises_normalization_error(self, tmp_path: Path):
        """F5 repro: a 4000x3 source into a 512x512 canvas has scale =
        min(512/4000, 512/3) = 0.128; the short axis (3 * 0.128 = 0.384)
        rounds down to 0 pixels. The pre-fix clamp (`max(1, ...)`) silently
        stretched that axis back up to 1px -- rendering content at an
        actual 512:1 pixel ratio while content_aspect_ratio kept reporting
        the true 1333.33 (4000/3) ratio, a field that lies about the pixels
        it accompanies. spec.md sec 6.2 forbids exactly this ('rather than
        silently crop, stretch, omit, or substitute'); this must now raise
        instead, naming the source and requested dimensions."""
        path = tmp_path / "extreme.png"
        Image.new("RGB", (4000, 3), (10, 200, 30)).save(path, format="PNG")

        with pytest.raises(NormalizationError, match=r"4000x3.*512x512"):
            normalize(path, target_size=(512, 512))

    def test_two_by_one_source_into_one_by_one_target_raises_normalization_error(
        self, tmp_path: Path
    ):
        """Round 3 finding C3: a 2x1 source into a 1x1 target has
        scale = min(1/2, 1/1) = 0.5, so the short axis's ideal scaled size
        is exactly 1 * 0.5 == 0.5. Python's `round()` uses banker's
        rounding (round-half-to-even), so `round(0.5) == 0` -- production
        correctly raises NormalizationError here, but the property test's
        old strict `< 0.5` degenerate check missed this exact boundary and
        only failed intermittently, whenever Hypothesis happened to
        generate this case. Pinned here so the boundary is covered on
        every run, not only when Hypothesis finds it."""
        path = tmp_path / "two_by_one.png"
        Image.new("RGB", (2, 1), (10, 200, 30)).save(path, format="PNG")

        with pytest.raises(NormalizationError):
            normalize(path, target_size=(1, 1))

    @given(
        source_w=st.integers(min_value=1, max_value=4000),
        source_h=st.integers(min_value=1, max_value=4000),
        target_w=st.integers(min_value=1, max_value=512),
        target_h=st.integers(min_value=1, max_value=512),
    )
    @settings(max_examples=50, deadline=None)
    def test_property_equal_axis_scale_over_arbitrary_dimensions(
        self, tmp_path_factory, source_w, source_h, target_w, target_h
    ):
        """Parameterized property test over non-square source dimensions
        (VQ-S3-004), extended (F8 remediation) to extreme aspect ratios that
        reach the F5 degenerate case (a scaled axis rounding down to 0
        pixels), which the original 20-900/32-512 ranges could never reach.

        F8: the expectation here is an independent oracle -- it does not
        restate `_scale_and_pad`'s internal `round(source * scale)`
        arithmetic (the earlier version of this test copied that formula,
        clamp included, verbatim, so it could never have caught a bug in
        that same formula). Instead it checks the invariants the spec
        actually requires -- content never exceeds the canvas, the per-axis
        scale factors implied by the MEASURED output pixels agree with each
        other, and the fit is 'contain'-tight against the bottleneck axis --
        directly against pixels, plus the degenerate-input contract (raise,
        don't stretch) added by F5.
        """
        tmp_dir = tmp_path_factory.mktemp("normalize_property")
        path = tmp_dir / "synthetic.png"
        Image.new("RGB", (source_w, source_h), (10, 200, 30)).save(path, format="PNG")

        scale = min(target_w / source_w, target_h / source_h)
        # The boundary the spec's "no stretch" guarantee draws: an ideal
        # scaled size at or below half a pixel rounds to 0, which can only
        # be honestly represented by rejecting, never by drawing a pixel.
        # Round 3 finding C3: `round()` uses banker's rounding
        # (round-half-to-even), so `round(0.5) == 0` -- a STRICT `< 0.5`
        # here missed that exact boundary (e.g. a 2x1 source into a 1x1
        # target: scale = 0.5, source_h * scale == 0.5 exactly), routing it
        # into the success branch below where production correctly raises
        # NormalizationError instead, an intermittent Hypothesis-dependent
        # failure. `<=` closes the boundary; see
        # test_two_by_one_source_into_one_by_one_target_raises_normalization_error
        # for a deterministic, non-property pin of this exact case.
        degenerate = (source_w * scale) <= 0.5 or (source_h * scale) <= 0.5

        if degenerate:
            with pytest.raises(NormalizationError):
                normalize(path, target_size=(target_w, target_h))
            return

        result = normalize(path, target_size=(target_w, target_h))

        assert result.content_aspect_ratio == pytest.approx(source_w / source_h)
        assert result.pixel_data.size == (target_w, target_h)

        min_x, min_y, max_x, max_y = _content_bounding_box(result.pixel_data, tolerance=20)
        measured_w = max_x - min_x + 1
        measured_h = max_y - min_y + 1

        # No crop: rendered content can never exceed the requested canvas.
        assert measured_w <= target_w
        assert measured_h <= target_h

        # Equal-axis scale (AC-PROCESS-1/2): the per-axis ratios implied by
        # the MEASURED output must agree with each other, to within one
        # source pixel's worth of rounding error -- checked against actual
        # pixels, not against the formula that produced them.
        observed_scale_w = measured_w / source_w
        observed_scale_h = measured_h / source_h
        scale_tolerance = 1.5 / min(source_w, source_h)
        assert observed_scale_w == pytest.approx(observed_scale_h, abs=scale_tolerance)

        # Tight "contain" fit: at least one axis' measured content size
        # must land within a pixel of its target, otherwise an arbitrarily
        # small (but still equal-axis) scale would pass the checks above.
        assert min(target_w - measured_w, target_h - measured_h) <= 1


class TestExifOrientation:
    """AC-PROCESS-1: EXIF orientation is applied before measuring content
    dimensions or aspect ratio (VQ-S3-007)."""

    def test_exif_orientation_corrects_stored_dimensions(self):
        """valid_exif_rotated.jpg is stored as 300x200 with an Orientation
        tag of 6 (rotate 90 deg CW); the corrected VISIBLE content is
        200x300 (portrait)."""
        with Image.open(FIXTURES_DIR / "valid_exif_rotated.jpg") as raw:
            stored_size = raw.size
        assert stored_size == (300, 200), "fixture assumption changed upstream"

        result = normalize(FIXTURES_DIR / "valid_exif_rotated.jpg", target_size=(300, 300))

        # Corrected content is portrait (200x300): aspect ratio must be
        # 200/300, not the stored 300/200.
        assert result.content_aspect_ratio == pytest.approx(200 / 300)
        assert result.content_aspect_ratio != pytest.approx(300 / 200)

    @given(
        source_w=st.integers(min_value=20, max_value=400),
        source_h=st.integers(min_value=20, max_value=400),
        orientation=st.sampled_from([1, 2, 3, 4, 5, 6, 7, 8]),
    )
    @settings(max_examples=25, deadline=None)
    def test_property_all_orientations_preserve_full_content_and_aspect(
        self, tmp_path_factory, source_w, source_h, orientation
    ):
        """Parameterized test across supported EXIF orientations and
        multiple non-square dimensions (VQ-S3-007): normalization retains
        full content and reports the corrected content aspect ratio for
        every orientation tag, produced by real EXIF handling in
        production code, not simulated in the test."""
        tmp_dir = tmp_path_factory.mktemp("exif_property")
        path = tmp_dir / "synthetic.jpg"

        image = Image.new("RGB", (source_w, source_h), (5, 5, 5))
        for x in range(source_w):
            for y in range(0, source_h, max(1, source_h // 8)):
                image.putpixel((x, y), (x % 256, y % 256, 40))
        exif = Image.Exif()
        exif[0x0112] = orientation
        image.save(path, format="JPEG", exif=exif.tobytes())

        with Image.open(path) as raw:
            from PIL import ImageOps

            corrected = ImageOps.exif_transpose(raw)
            expected_w, expected_h = corrected.size

        result = normalize(path, target_size=(512, 512))

        assert (result.pixel_data.width, result.pixel_data.height) == (512, 512)
        assert result.content_aspect_ratio == pytest.approx(expected_w / expected_h)


class TestAlphaCompositing:
    """AC-PROCESS-2: an alpha-channel source is composited onto
    NEUTRAL_FILL_VALUE before conversion, with a pixel-level assertion
    (VQ-S3-008), not merely 'mode == RGB'."""

    def test_transparent_region_becomes_neutral_fill_not_undefined(self):
        with Image.open(FIXTURES_DIR / "valid_alpha.png") as src:
            assert src.mode == "RGBA"
            source_size = src.size  # (200, 100)

        result = normalize(FIXTURES_DIR / "valid_alpha.png", target_size=source_size)

        assert result.pixel_data.mode == "RGB"
        pixels = result.pixel_data.load()
        # Left half is opaque red (255, 0, 0, 255) in the source fixture.
        assert pixels[10, 10][:3] == (255, 0, 0)
        # Right half is fully transparent -> must composite to the exact
        # documented neutral fill, never white/black/undefined.
        assert pixels[150, 10][:3] == _FILL_RGB

    def test_composited_alpha_fill_and_padding_fill_coexist_on_one_canvas(self):
        """F11: every other alpha test above uses target_size == source_size
        or None, so the composited-alpha fill and the centered-padding fill
        never appear on the SAME canvas at once -- the one scenario that
        would catch a later story splitting NEUTRAL_FILL_VALUE's two uses
        (alpha compositing vs. padding) into two different constants,
        which spec.md sec 6.2 and the ledger concept neutral-fill-binding
        forbid. Normalizing the 200x100 valid_alpha.png fixture onto a
        300x300 canvas scales it by 1.5 (scaled content 300x150) and pads
        top/bottom by 75px each, producing both a composited-alpha region
        (inside the content band, on the source's transparent right half)
        and a padding region (outside the content band entirely) on one
        output."""
        with Image.open(FIXTURES_DIR / "valid_alpha.png") as src:
            assert src.mode == "RGBA"
            assert src.size == (200, 100)

        result = normalize(FIXTURES_DIR / "valid_alpha.png", target_size=(300, 300))
        pixels = result.pixel_data.load()

        # Padding region: outside the pasted content band (content occupies
        # canvas y in [75, 225); rows 0-74 and 225-299 are pure padding,
        # never touched by the source image at all).
        assert pixels[10, 10][:3] == _FILL_RGB  # top padding band
        assert pixels[10, 290][:3] == _FILL_RGB  # bottom padding band

        # Composited-alpha region: INSIDE the content band, deep within the
        # source's formerly-transparent right half (scaled: original x=100
        # maps to canvas x=150, so x=280 is well clear of both that seam
        # and the canvas edge).
        assert pixels[280, 150][:3] == _FILL_RGB

        # Sanity: the opaque left half survives scaling with its original
        # color, proving the assertion above is genuinely exercising alpha
        # compositing and not accidentally landing in padding too.
        assert pixels[10, 150][:3] == (255, 0, 0)

    def test_rgb_colorkey_transparency_composites_to_neutral_fill(self):
        """Round 3 finding C1: a PNG's tRNS chunk can designate a single
        color-key as "transparent" WITHOUT the image being in RGBA/LA/P
        mode at all -- an RGB (or grayscale) source can carry a color-keyed
        tRNS chunk and still decode in mode "RGB", with the key recorded
        only in `image.info["transparency"]`. Before the fix, such sources
        took the direct `.convert("RGB")` branch and exposed the
        underlying key color (green, here) instead of the neutral fill --
        this fixture's right half is exactly that: color-keyed green, not
        a real alpha channel."""
        with Image.open(FIXTURES_DIR / "valid_rgb_colorkey_transparency.png") as src:
            assert src.mode == "RGB"
            assert "transparency" in src.info
            source_size = src.size  # (200, 100)

        result = normalize(
            FIXTURES_DIR / "valid_rgb_colorkey_transparency.png", target_size=source_size
        )

        assert result.pixel_data.mode == "RGB"
        pixels = result.pixel_data.load()
        # Left half is opaque red (255, 0, 0) in the source fixture.
        assert pixels[10, 10][:3] == (255, 0, 0)
        # Right half is the color-keyed "transparent" green -> must
        # composite to the exact documented neutral fill, never the raw
        # green key color.
        assert pixels[150, 10][:3] == _FILL_RGB


class TestDeterminism:
    """AC-PROCESS-2: identical output for the same source bytes and
    target_size, on repeated runs, independent of available resources.
    decoded_at is explicitly excluded (see NormalizedReference docstring)."""

    def test_repeated_normalization_is_byte_identical(self):
        path = FIXTURES_DIR / "valid_portrait.png"
        target_size = (333, 217)  # deliberately not a clean multiple

        first = normalize(path, target_size=target_size)
        second = normalize(path, target_size=target_size)

        assert first.pixel_data.tobytes() == second.pixel_data.tobytes()
        assert first.width == second.width
        assert first.height == second.height
        assert first.content_aspect_ratio == second.content_aspect_ratio
        assert first.fill_value == second.fill_value
        # decoded_at is provenance, not covered by the determinism invariant.

    def test_determinism_independent_of_max_image_pixels_headroom(self, monkeypatch):
        """Raising the resource ceiling (more 'available resources') must
        not change the produced pixels -- the scale factor is not a
        function of resource headroom."""
        path = FIXTURES_DIR / "valid_square.png"
        target_size = (150, 150)

        baseline = normalize(path, target_size=target_size)

        monkeypatch.setattr(Image, "MAX_IMAGE_PIXELS", Image.MAX_IMAGE_PIXELS * 100)
        with_more_headroom = normalize(path, target_size=target_size)

        assert baseline.pixel_data.tobytes() == with_more_headroom.pixel_data.tobytes()


class TestOptionalTargetSize:
    """Decider ruling 2026-09-18 (S3 Stage-1 review finding F2, spec.md sec
    6.2 items 3/4 are each conditional on the selected model): target_size
    is optional. `None` means apply EXIF orientation, RGB conversion, and
    alpha compositing only -- no scaling, no padding -- returning the image
    at its EXIF-corrected source dimensions."""

    def test_none_target_size_skips_scaling_and_returns_source_dimensions(self):
        with Image.open(FIXTURES_DIR / "valid_landscape.jpg") as src:
            source_size = src.size  # (600, 400); this fixture carries no EXIF tag

        result = normalize(FIXTURES_DIR / "valid_landscape.jpg", target_size=None)

        assert result.pixel_data.mode == "RGB"
        assert result.pixel_data.size == source_size
        assert result.width == source_size[0]
        assert result.height == source_size[1]
        assert result.content_aspect_ratio == pytest.approx(source_size[0] / source_size[1])
        assert result.fill_value == NEUTRAL_FILL_VALUE

    def test_target_size_omitted_defaults_to_none(self):
        """target_size defaults to None, not a required argument."""
        explicit = normalize(FIXTURES_DIR / "valid_square.png", target_size=None)
        omitted = normalize(FIXTURES_DIR / "valid_square.png")

        assert explicit.pixel_data.size == omitted.pixel_data.size
        assert explicit.width == omitted.width
        assert explicit.height == omitted.height

    def test_none_target_size_still_applies_exif_orientation(self):
        """EXIF orientation must still be corrected even without a fixed
        canvas: valid_exif_rotated.jpg is stored 300x200 with an
        Orientation tag of 6 (rotate 90deg CW); the corrected visible
        content is 200x300."""
        result = normalize(FIXTURES_DIR / "valid_exif_rotated.jpg", target_size=None)

        assert result.pixel_data.size == (200, 300)
        assert result.width == 200
        assert result.height == 300
        assert result.content_aspect_ratio == pytest.approx(200 / 300)

    def test_none_target_size_still_composites_alpha_onto_neutral_fill(self):
        with Image.open(FIXTURES_DIR / "valid_alpha.png") as src:
            assert src.mode == "RGBA"
            source_size = src.size  # (200, 100)

        result = normalize(FIXTURES_DIR / "valid_alpha.png", target_size=None)

        assert result.pixel_data.mode == "RGB"
        assert result.pixel_data.size == source_size
        pixels = result.pixel_data.load()
        assert pixels[10, 10][:3] == (255, 0, 0)
        assert pixels[150, 10][:3] == _FILL_RGB

    def test_none_target_size_produces_no_padding(self):
        """No fill-colored margin: the output is exactly the
        (EXIF-corrected, RGB-converted) source content, since there is no
        canvas larger than the content to pad into."""
        result = normalize(FIXTURES_DIR / "valid_landscape.jpg", target_size=None)

        min_x, min_y, max_x, max_y = _content_bounding_box(result.pixel_data)
        width, height = result.pixel_data.size
        assert (min_x, min_y) == (0, 0)
        assert (max_x, max_y) == (width - 1, height - 1)

    def test_none_target_size_never_raises_normalization_error(self, monkeypatch):
        """NormalizationError is specific to the scale/pad stage; that
        stage never runs when target_size is None, so it must never be
        raised even if _scale_and_pad itself would have failed."""
        monkeypatch.setattr(
            normalize_module,
            "_scale_and_pad",
            lambda *args, **kwargs: (_ for _ in ()).throw(AssertionError("must not be called")),
        )

        result = normalize(FIXTURES_DIR / "valid_landscape.jpg", target_size=None)
        assert isinstance(result, NormalizedReference)


class TestTargetSizeValidation:
    """F10: normalize()'s docstring documents a ValueError for a malformed
    target_size (not a pair of positive integers), but the optional-
    parameter change (target_size: tuple[int, int] | None = None) made
    this a two-branch path -- `target_size is None` skips validation
    entirely, `target_size is not None` validates it -- and neither branch
    had a test."""

    @pytest.mark.parametrize(
        "malformed_target_size",
        [
            (0, 64),  # zero width
            (64, -1),  # negative height
            (64,),  # wrong arity: unpacking itself raises ValueError
        ],
    )
    def test_malformed_target_size_raises_value_error(self, malformed_target_size):
        with pytest.raises(ValueError):
            normalize(FIXTURES_DIR / "valid_landscape.jpg", target_size=malformed_target_size)

    def test_none_target_size_bypasses_validation_entirely(self):
        """The `target_size is None` branch must reach neither the
        unpacking nor the positivity check -- confirmed by the fact that
        None itself would fail both if it were run through them."""
        result = normalize(FIXTURES_DIR / "valid_landscape.jpg", target_size=None)
        assert isinstance(result, NormalizedReference)


class TestSourcePreservation:
    """spec.md sec 6.1: references are opened read-only; normalize() must
    never write to, rename, or relocate the source file."""

    def test_source_file_untouched_after_normalize(self, tmp_path: Path):
        source = tmp_path / "source.png"
        shutil.copy(FIXTURES_DIR / "valid_portrait.png", source)
        original_bytes = source.read_bytes()
        original_mtime = source.stat().st_mtime_ns

        normalize(source, target_size=(64, 64))

        assert source.read_bytes() == original_bytes
        assert source.stat().st_mtime_ns == original_mtime
        assert source.exists()
